### ISSUE TITLE
Two things that bothered me while using the Pokemon tool

### ISSUE THREAD

**Issue by SuzumiDev** [antialiasis/favorite-picker#27]
This is mostly just things I've noticed could be better after using the Pokemon picker just now, apologies if these have previously been mentioned in other issues (I believe one has but the response to it seems different from how it actually works in the current tool).

- Pass button
When pressing the pass button, I feel like it should eliminate every option on the screen as indifferent, as the UI suggests. Currently, it does not do that, instead moving on to the next batch while leaving the current batch still in the pool. This makes end-of-rounds with lots of random selections very annoying to deal with, as you have to click pass a lot of times until finally getting one you like with which you can start eliminating the others.

- New rounds
After choosing a favourite, the intended functionality seems to be to take the other most picked from the pool and display those. Instead sometimes a new round will just soft-reset the system and show things that already have been shown and most of the times even never picked. Say in the Pokemon for example I could see mons I didn't pick in the very first round well into picking my 20th favourite, while ones I had picked a lot of times I didn't see again until favourite 30. I don't know if this is intended behaviour, or a bug. In either case, I'd like to give my opinion that things that are chosen multiple times should get priority, and if this is intended behaviour it should have some looking into as it clearly doesn't seem to be working well.

I think two years ago I used this tool, and the second point was working as I describe it, so I don't know what has changed, but if it's intended behaviour then I'd argue this is worse.

**Comment by antialiasis** [comment]
Your mental model of how the picker works internally is a bit off. It does not track *how often* you pick anything, only *which Pokémon were eliminated by which ones*. Pokémon that have been eliminated will not appear again until *all the Pokémon that eliminated them* (i.e. the ones you picked over them from their batch) have been added to the favorite list - at that point, any of them might be your next favorite, because all we know is that you liked these Pokémon you already have on your list more than them.

This is why passing does not eliminate all the options - there is nothing they were *eliminated by*, so if we eliminated them, we would have no information to know when we should bring those Pokémon back into the running! Instead, passing is equivalent to *picking all of the Pokémon you're looking at, eliminating none*. In order to progress, you need to eliminate and not just pass.

In each run of looking for a favorite, you will need to eventually eliminate every Pokémon in that run but one - that's how we know to put it next on the list. So it does not really make sense to "give priority" to certain Pokémon - you'll have to go through all of the ones in the running either way to be sure which your second favorite is.

(Note that a *run*, from one favorite being added to the list to the next, is different from a *round*. You may have seen me talking about rounds when commenting on another ticket. Each *round* is one cycle through all of the Pokémon still present (not yet eliminated) in this *run*. In the next round, you'll be shown only the Pokémon you picked (or passed on) from the previous round (+ possibly a few stragglers that would have come at the end of the previous round but didn't make a full batch), until you've eliminated every Pokémon in that *run* except one. Once you've done that, that Pokémon is put on your list and the *run* ends, and the next run begins; that run will contain all of the Pokémon that were *at some point eliminated by that final pick from the previous run*, whether that was in the first or tenth round of that run. If you pick consistently in accordance with your preferences, then your second favorite Pokémon has to be somewhere among this set, but cannot be among whatever Pokémon you might have picked *often* but were then eliminated by something other than your top favorite.)

The algorithm works this way - making you eliminate every Pokémon but one, then bringing back the ones eliminated by that Pokémon and making you eliminate all but one again - because that's a consistent way to shake out your actual preferences if you pick consistently, without being skewed by the random chance of which Pokémon happen to have been matched against which when. This is how it has worked since I first made it, so I'm not sure what you mean about it working differently two years ago.

**Comment by SuzumiDev** [comment]
Thanks for clarifying what I got wrong. It seems my memory did not serve me well in terms of  how it has worked in the past.

In the case of the pass button working this way, I would suggest to either use a dummy id to register it as eliminated by, as it is (in my opinion) not a good user experience to have to keep pressing pass on 2 choices until you finally get something that you can eliminate another choice with.

As for the "runs", I think it could use some improvement. You say that Pokemon eliminated by your favourite are returned in the next run, but currently this causes a loop of the next run containing Pokemon that the user is indifferent to (as at some point early on that one was chosen among many others), which are then eliminated again, and then in the next run most of those end up returning once again. I think a way of improving this would be to make sure if something never eliminates another Pokemon (i.e. never appears as eliminatedBy), but it has been eliminated before, then it should never appear again in another run, even if it was eliminated by the previous favourite. Of course performance would be a factor in making this possible, so I'm not saying my idea is the best, but I do think that adding something like that would improve the selection of the next run. Also, my idea for usage of the pass button could also improve this issue now that I think of it.

**Comment by antialiasis** [comment]
The problem is your suggestions don’t work algorithmically; they would make the picker stop working accurately.

Say your second favorite Pokémon just so happens to appear in a batch with your very favorite in the first round. You pick your favorite, because it’s your favorite. Well, you’re suggesting that now your second favorite should just be gone forever, because it got eliminated but never got picked! I find that a deeply undesirable result that would defeat the whole point of the picker.

And similarly, if passed Pokémon get eliminated with a dummy ID - that would mean these Pokémon just get eliminated forever. But then some other Pokémon you don’t care about either that merely *happened* to appear in a batch with some Pokémon you wanted to pick don’t get eliminated forever that way. The whole thing gets skewed based on how it happens to randomly assign Pokémon to batches. I made this picker specifically because I wanted a tool with an algorithm that *works*, that will actually construct an arbitrarily long list based on your expressed preferences without being skewed by some kind of random chance.

In general, the picker is not designed for you to pass constantly - to progress you need to express preferences, even if it’s a preference between two Pokémon you don’t like. (Because picking a Pokémon doesn’t give it “points” in any way, this won’t wrongly make the picker think you actually *like* that Pokémon - only that you prefer it over the other one.) The user experience of constantly passing between the same two Pokémon is one that you’re creating for yourself by constantly passing!

That said, I have been musing on something that might be helpful to people like you, which would let you effectively start by sectioning the entire list into Pokémon you like and ones you don’t, effectively treating all the ones you don’t pick or pass on as eliminated by all the ones you did pick across the full round. That would remain algorithmically sound (more or less; it would rely on your bar for which Pokémon you’re willing to pick not wobbling too much between batches) while letting you get rid of all Pokémon you don’t care about until the theoretical point *all* the Pokémon you picked as liked have been added to your list. I think this would probably solve your frustrations, and those of others with similar qualms, without majorly compromising the integrity of the tool.

**Comment by antialiasis** [comment]
> You say that Pokemon eliminated by your favourite are returned in the next run, but currently this causes a loop of the next run containing Pokemon that the user is indifferent to (as at some point early on that one was chosen among many others), which are then eliminated again, and then in the next run most of those end up returning once again.

I should also mention - you won’t see *most* of those Pokémon returning in a loop; rather, the ones you see again are exactly those Pokémon that only ever got eliminated by your first and second favorites. Based on the information we have, these are all Pokémon that *could* be your third favorite. There is no redundancy - every preference that you expeess at any point is permanently taken into account and you will never have to express the same preference again, or a redundant preference (i.e. if you’ve said you like A more than B, and B more than C, you will never be made to also tell it that you like A more than C). Getting the same comparisons cropping up again is something that will only happen if you pass.

**Comment by SuzumiDev** [comment]
I think the main problem with the way the algorithm works is that it seems, to me, to be designed for a UI that only allows you to pick one at a time, which isn't true in the current UI. If you get presented with 30 options, there's bound to be multiple you like, and those are the ones you click. But then the ones eliminated end up being thrown back into the mix once the ones you picked in that batch are picked as favourites. The solution you mentioned seems to be the fix to this issue, and I look forward to seeing what you do with it.

**Comment by antialiasis** [comment]
It’s true people might be *unlikely* to pick just their top favorite from a batch that also includes their second favorite - but what about their tenth favorite, which doesn’t really register when they’re looking at it alongside their top favorite but actually does belong on their list? What about their twentieth favorite? (A *lot* of people use the picker to construct lists well beyond twenty favorites, so this is by no means irrelevant - if the twentieth favorite gets eliminated forever in the first round by bad luck, then their list’s going to end up wrong.) And what about those users who go on to construct lists of hundreds? Which, yes, people do do that (I’ve had several people e-mail me about how they just finished ordering *every single Pokémon* using the picker). It’s a massive can of worms and inaccuracies once you start eliminating anything forever.

The current elimination algorithm is designed to work correctly regardless of how many you pick - if you pick multiple Pokémon from the batch, then the ones you didn’t pick will return when *all* of the ones you did pick are on the favorite list. Which is correct - what we know is that you like the ones you picked better than the ones you didn’t, so once they’re all on the list, the ones you didn’t pick might come at any point after that. This applies regardless of whether you pick just your very favorite from the batch or pick half the batch, so your picking strategy, the bar for what you’re willing to pick, is flexible and up to you (and in the current mode, it can also shift from batch to batch without affecting your ultimate results - the new mode would rely on the user being able to keep that bar reasonably consistent for the full round, though, and the UI will need to make that very clear).

But as I said, I think the new mode I’m thinking of will help eliminate most of the frustration of having to pick between Pokémon you don’t care about while remaining algorithmically sound, so I hope that will do the job and make it less annoying for you!

I put a lot of thought into the algorithm and why and how it works, as you can see, heh. Sorry for the longwinded explanations; I do really appreciate the feedback, and hearing from you helped me solidify this new mode idea and how to go about it, so thank you very much for that.
